insert into persona (numero, calle, nombre) values (123, 'calle', 'Pedro');
insert into persona (numero, calle, nombre) values (1234, 'calle2', 'Miguel');
insert into persona (numero, calle, nombre) values (12345, 'calle3', 'Luis');

insert into telefono (numero, codigo_area, persona_id) values (1234, 341, 1);
insert into telefono (numero, codigo_area, persona_id) values (12345, 341, 1);
insert into telefono (numero, codigo_area, persona_id) values (123456, 341, 2);

insert into usuario (username, password, email, enabled) values ('gscarffe0', 'yE4$qM~7c''/e', 'bskitteral0@epa.gov', true);
insert into usuario (username, password, email, enabled) values ('vwitson1', 'mF0)_''$NV', 'rvirgo1@aboutads.info', true);
insert into usuario (username, password, email, enabled) values ('gyetts2', 'lG1}b\<*b', 'aalbisser2@arizona.edu', false);
insert into usuario (username, password, email, enabled) values ('ajollands3', 'uO4*x%9h7WnX@("~', 'pdemico3@360.cn', true);
insert into usuario (username, password, email, enabled) values ('sesselin4', 'iL3?Jg{|9', 'cfitzpayn4@sfgate.com', true);
insert into usuario (username, password, email, enabled) values ('gjanodet5', 'gL0{4\m=4', 'egillyett5@google.com.au', true);
insert into usuario (username, password, email, enabled) values ('erosenbaum6', 'xZ0\y%Y~Y', 'gjanca6@ed.gov', true);
insert into usuario (username, password, email, enabled) values ('rcastanares7', 'zV7+$7w%lpb', 'dbeacom7@ning.com', false);
insert into usuario (username, password, email, enabled) values ('hlynnett8', 'qS0?sXRdOC4d', 'kmcgrae8@reference.com', false);
insert into usuario (username, password, email, enabled) values ('cdunridge9', 'eE3..FJazH/P', 'gmissen9@instagram.com', true);
insert into usuario (username, password, email, enabled) values ('cmeadsa', 'kJ1"#n8U', 'wannona@omniture.com', false);
insert into usuario (username, password, email, enabled) values ('sbrokenshireb', 'nU7_G\Mp?', 'dkibbelb@cargocollective.com', false);
insert into usuario (username, password, email, enabled) values ('cpurslowc', 'bF9+"TG57mE', 'fmathysc@deviantart.com', true);
insert into usuario (username, password, email, enabled) values ('adodingd', 'qR1\sB{z5W''4', 'amineghellid@yahoo.co.jp', false);
insert into usuario (username, password, email, enabled) values ('kdudlistone', 'kQ9{j_Agg', 'dhicke@weebly.com', false);
insert into usuario (username, password, email, enabled) values ('msinisburyf', 'pX2)In=vsDe31CQ@', 'ptesdalef@behance.net', false);
insert into usuario (username, password, email, enabled) values ('mweadickg', 'aY2/zLza=eSdxIa%', 'kmaxworthyg@technorati.com', false);
insert into usuario (username, password, email, enabled) values ('mdurbinh', 'pM6(ylp*!PT', 'ekleinhaush@typepad.com', false);
insert into usuario (username, password, email, enabled) values ('tscardefieldi', 'qS6!pxGDRP.zD', 'ofableri@skype.com', false);
insert into usuario (username, password, email, enabled) values ('hemmersonj', 'gY6<`I<M`K$,a', 'ddoughertyj@fotki.com', false);
insert into usuario (username, password, email, enabled) values ('etomank', 'lO5>%Q`rS', 'dsansumk@army.mil', false);
insert into usuario (username, password, email, enabled) values ('elekeuxl', 'uZ9?s$QjT<`*F7w9', 'hyatel@shop-pro.jp', false);
insert into usuario (username, password, email, enabled) values ('rshyresm', 'hD7&4uoXMt"%z', 'acahalinm@soup.io', true);
insert into usuario (username, password, email, enabled) values ('rdriesn', 'uA9*kP>!x`', 'ibottomoren@chicagotribune.com', false);
insert into usuario (username, password, email, enabled) values ('hdawsono', 'eU9_Qui5/eYJ<"6T', 'ltodmano@netlog.com', true);
insert into usuario (username, password, email, enabled) values ('hcarriganp', 'oB8}+(@YH', 'tleatherborrowp@nsw.gov.au', true);
insert into usuario (username, password, email, enabled) values ('bcartmaleq', 'kI2"fzvo&', 'abinneq@apache.org', true);
insert into usuario (username, password, email, enabled) values ('ehrinchishinr', 'oK7''K{g*', 'kperrycostr@dyndns.org', false);
insert into usuario (username, password, email, enabled) values ('cslaughters', 'uU7*Bo,{', 'mbazoches@photobucket.com', true);
insert into usuario (username, password, email, enabled) values ('nvoddent', 'dV9$ai+lDL+5g~\', 'baierst@msn.com', false);
insert into usuario (username, password, email, enabled) values ('yhudlestonu', 'hR4%ZVz"xrG|~k2h', 'malisonu@umich.edu', true);
insert into usuario (username, password, email, enabled) values ('bblivenv', 'eP3/aNZVG|yTr+', 'zhayerv@comsenz.com', false);
insert into usuario (username, password, email, enabled) values ('gkirkew', 'rX0*~5@$V9>JhQY', 'dtromansw@angelfire.com', true);
insert into usuario (username, password, email, enabled) values ('cegellx', 'aQ5_gGLCHUS6fH', 'cpapesx@hud.gov', false);
insert into usuario (username, password, email, enabled) values ('cprykey', 'jM4/(\FZlwgph}u', 'alewryy@ebay.co.uk', true);
insert into usuario (username, password, email, enabled) values ('dburginz', 'iE0*u=$q}a_H', 'fdummerz@t.co', true);
insert into usuario (username, password, email, enabled) values ('robal10', 'qJ4.8%50LIBsNse', 'bfehner10@ed.gov', false);
insert into usuario (username, password, email, enabled) values ('bsabater11', 'dC5!j8Y/', 'tbendelow11@microsoft.com', true);
insert into usuario (username, password, email, enabled) values ('hhub12', 'vL2*IMdn{gm".?', 'sheaphy12@yolasite.com', false);
insert into usuario (username, password, email, enabled) values ('coughtright13', 'vZ3{()dUy1vhM{!I', 'bcaistor13@stanford.edu', false);
insert into usuario (username, password, email, enabled) values ('nconsidine14', 'mG6/p63tUPJc', 'rhrishanok14@seattletimes.com', false);
insert into usuario (username, password, email, enabled) values ('dcroisier15', 'jX2(RHSV''_s', 'ahuyche15@ftc.gov', false);
insert into usuario (username, password, email, enabled) values ('wlomaz16', 'cW1|QTZs', 'epeter16@dell.com', true);
insert into usuario (username, password, email, enabled) values ('bhamlin17', 'oV2"ZEp4Wa8B/.', 'jmacdermand17@dropbox.com', true);
insert into usuario (username, password, email, enabled) values ('aburbury18', 'uD0$mXYL', 'mmotto18@cisco.com', true);
insert into usuario (username, password, email, enabled) values ('cmceachern19', 'zO3``?PY', 'bjosh19@symantec.com', false);
insert into usuario (username, password, email, enabled) values ('aberkeley1a', 'zT1(vHI*I?\', 'aeilhersen1a@printfriendly.com', false);
insert into usuario (username, password, email, enabled) values ('cdelucia1b', 'qX6_X*D4Lw*', 'mcund1b@sbwire.com', true);
insert into usuario (username, password, email, enabled) values ('fspring1c', 'oX6\DL@+X=tk', 'ddecruze1c@go.com', false);
insert into usuario (username, password, email, enabled) values ('hkirk1d', 'oC1|lV@67', 'brockhall1d@shop-pro.jp', false);
